# ==============================================================================
# Security Limits for Gaming & Wine Fsync/Esync
# ==============================================================================
*               hard    nofile          1048576
*               soft    nofile          1048576
*               hard    memlock         unlimited
*               soft    memlock         unlimited
*               hard    nice            -20
*               soft    nice            -20
