# ==============================================================================
# Calamares Mount Configuration (High Performance SSD Flags)
# ==============================================================================
extraMounts:
    - device: proc
      fs: proc
      mountPoint: /proc
    - device: sys
      fs: sysfs
      mountPoint: /sys
    - device: /dev
      mountPoint: /dev
      options: [ bind ]
    - device: tmpfs
      fs: tmpfs
      mountPoint: /run
    - device: /run/udev
      mountPoint: /run/udev
      options: [ bind ]

btrfsMountOptions:
    - filesystem: btrfs
      options: [ "defaults", "noatime", "compress=zstd:3", "discard=async", "space_cache=v2" ]
