# ==============================================================================
# Calamares User Module Configuration
# ==============================================================================
defaultGroups:
    - wheel
    - gamemode
    - video
    - audio
    - input
    - storage
    - optical
    - network
    - power

autologinGroup: autologin
sudoersGroup: wheel
setRootPassword: false
doAutologin: false
passwordRequirements:
    nonempty: true
    minLength: 1
