# ==============================================================================
# Calamares Welcome Module Configuration
# ==============================================================================
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
    requiredStorage:    30.0
    requiredRam:        4.0
    internetCheckUrl:   http://detectportal.firefox.com/canonical.html
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
