# ==============================================================================
# Calamares Settings Configuration - Gaming OS
# ==============================================================================
modules-search: [ local ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkmanager
      - hwclock
      - services-systemd
      - bootloader
      - shellprocess
      - umount
  - show:
      - finished

branding: default
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
